apiVersion: v1
kind: Service
metadata:
  name: {{ include "twc-lab.fullname" . }}-artemis
  labels:
    {{- include "twc-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: artemis
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "twc-lab.componentSelectorLabels" (dict "root" . "component" "artemis") | nindent 4 }}
  ports:
    - name: core
      port: 61616
      targetPort: core
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "twc-lab.fullname" . }}-artemis
  labels:
    {{- include "twc-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: artemis
spec:
  serviceName: {{ include "twc-lab.fullname" . }}-artemis
  replicas: {{ .Values.artemis.replicaCount }}
  selector:
    matchLabels:
      {{- include "twc-lab.componentSelectorLabels" (dict "root" . "component" "artemis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "twc-lab.componentSelectorLabels" (dict "root" . "component" "artemis") | nindent 8 }}
    spec:
      containers:
        - name: artemis
          image: "{{ .Values.artemis.image.repository }}:{{ .Values.artemis.image.tag }}"
          imagePullPolicy: {{ .Values.artemis.image.pullPolicy }}
          env:
            - name: ARTEMIS_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "twc-lab.fullname" . }}-artemis
                  key: username
            - name: ARTEMIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "twc-lab.fullname" . }}-artemis
                  key: password
            - name: ANONYMOUS_LOGIN
              value: "false"
          ports:
            - name: core
              containerPort: 61616
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: core
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: core
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            {{- toYaml .Values.artemis.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/artemis-instance
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.storageClass.name }}
        resources:
          requests:
            storage: {{ .Values.artemis.persistence.size }}
