apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twc-lab.componentName" (dict "root" . "component" "artemis") }}
  labels:
    {{- include "twc-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: artemis
type: Opaque
immutable: true
stringData:
  username: {{ .Values.secrets.artemisUser | quote }}
  password: {{ required "secrets.artemisPassword is required" .Values.secrets.artemisPassword | quote }}
