apiVersion: v1
kind: Secret
metadata:
  name: {{ include "twc-lab.fullname" . }}-artemis
  labels:
    {{- include "twc-lab.labels" . | nindent 4 }}
    app.kubernetes.io/component: artemis
type: Opaque
stringData:
  username: {{ .Values.secrets.artemisUser | quote }}
  password: {{ required "secrets.artemisPassword is required" .Values.secrets.artemisPassword | quote }}
